const char* ERROR_STRINGS[] =
{
//English
    "Success",
    "FileNotFound",
    "ShellOpen",
    "WrongMedia",
    "There's a problem with the disc you're using. It may be dirty or damaged. Press A to continue.",
    "There's a problem with the disc you're using. It may be dirty or damaged. Press A to continue.",
    "There's a problem with the disc you're using. It may be dirty or damaged. Press A to continue.",
    "There is not enough free disk space to save the game. Free some space and try again.",
    "A disk error occurred while saving the game. Please try again.",
    "MediaEncodingErr",
    "MediaWrongType",
    "MediaInvalid",
    "DataCorrupt",
//French
    "NON SOUTENU",
    "NON SOUTENU",
    "NON SOUTENU",
    "NON SOUTENU",
    "ÉCHEC DE MATÉRIEL",
    "ÉCHEC DE MATÉRIEL",
    "ÉCHEC DE MATÉRIEL",
    "ÉCHEC DE MATÉRIEL",
    "HORS DE L'ESPACE",
    "NON SOUTENU",
    "NON SOUTENU",
    "NON SOUTENU",
    "NON SOUTENU",
};
